baseURL = "https://blog.nostr.club"
languageCode = "en-us"
title = "nostr.club ✦ Blog"
theme = "PaperMod"
paginate = 10

[params]
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  ShowShareButtons = true

[params.homeInfoParams]
  Title = "⚡ Welcome to nostr.club"
  Content = """The home of NIP-05 vanity identities, Lightning-powered profiles, and censorship-resistant social presence.

This blog covers everything from Nostr tips to building your zap-enabled identity on the decentralized web."""

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/nostrclub"

[[params.socialIcons]]
  name = "website"
  url = "https://nostr.club"

[[menu.main]]
  name = "Guides"
  url = "/guides/"
  weight = 1

[[menu.main]]
  name = "Updates"
  url = "/updates/"
  weight = 2

[[menu.main]]
  name = "Profiles"
  url = "/profiles/"
  weight = 3
