baseURL = "https://blog.nostr.club"
languageCode = "en-us"
title = "nostr.club blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "Welcome to nostr.club"
  Content = "Identity. Lightning. Censorship resistance."

[[menu.main]]
  name = "Home"
  url = "/"
