baseURL = "https://blog.nostr.club"
languageCode = "en-us"
title = "nostr.club's blog"
theme = "PaperMod"

[params]
  homeInfoParams = { Title = "Welcome to nostr.club", Content = "This is your Hugo homepage." }
